python train_net.py --resume --num-gpus 4 --config configs/Faster-RCNN/nightowls/faster_rcnn_R_50_FPN_ut2_sup0.08_run0.yaml SOLVER.IMG_PER_BATCH_LABEL 4 SOLVER.IMG_PER_BATCH_UNLABEL 4 MODEL.WEIGHTS /home/hkhachatrian/unbiased_teacher/unbiased-teacher-v2/output/burn_up_250_const_threshold_sup_loss_weight_1/model_0000249.pth EXPERIMENT_NAME 'constant_0.7' SEMISUPNET.PSEUDO_BBOX_SAMPLE 'constant' OUTPUT_DIR './output/constant_0.7'
python train_net.py --resume --num-gpus 4 --config configs/Faster-RCNN/nightowls/faster_rcnn_R_50_FPN_ut2_sup0.08_run0.yaml SOLVER.IMG_PER_BATCH_LABEL 4 SOLVER.IMG_PER_BATCH_UNLABEL 4 MODEL.WEIGHTS /home/hkhachatrian/unbiased_teacher/unbiased-teacher-v2/output/burn_up_250_const_threshold_sup_loss_weight_1/model_0000249.pth EXPERIMENT_NAME 'equal_90_percentile' SEMISUPNET.PSEUDO_BBOX_SAMPLE 'equal_90_percentile' OUTPUT_DIR './output/equal_90_percentile'
python train_net.py --resume --num-gpus 4 --config configs/Faster-RCNN/nightowls/faster_rcnn_R_50_FPN_ut2_sup0.08_run0.yaml SOLVER.IMG_PER_BATCH_LABEL 4 SOLVER.IMG_PER_BATCH_UNLABEL 4 MODEL.WEIGHTS /home/hkhachatrian/unbiased_teacher/unbiased-teacher-v2/output/burn_up_250_const_threshold_sup_loss_weight_1/model_0000249.pth EXPERIMENT_NAME 'class-specific_90_percentile' SEMISUPNET.PSEUDO_BBOX_SAMPLE 'class-specific_90_percentile' OUTPUT_DIR './output/class-specific_90_percentile'
python train_net.py --resume --num-gpus 4 --config configs/Faster-RCNN/nightowls/faster_rcnn_R_50_FPN_ut2_sup0.08_run0.yaml SOLVER.IMG_PER_BATCH_LABEL 4 SOLVER.IMG_PER_BATCH_UNLABEL 4 MODEL.WEIGHTS /home/hkhachatrian/unbiased_teacher/unbiased-teacher-v2/output/burn_up_250_const_threshold_sup_loss_weight_1/model_0000249.pth EXPERIMENT_NAME 'equal_95_percentile' SEMISUPNET.PSEUDO_BBOX_SAMPLE 'equal_95_percentile' OUTPUT_DIR './output/equal_95_percentile'
python train_net.py --resume --num-gpus 4 --config configs/Faster-RCNN/nightowls/faster_rcnn_R_50_FPN_ut2_sup0.08_run0.yaml SOLVER.IMG_PER_BATCH_LABEL 4 SOLVER.IMG_PER_BATCH_UNLABEL 4 MODEL.WEIGHTS /home/hkhachatrian/unbiased_teacher/unbiased-teacher-v2/output/burn_up_250_const_threshold_sup_loss_weight_1/model_0000249.pth EXPERIMENT_NAME 'class-specific_95_percentile' SEMISUPNET.PSEUDO_BBOX_SAMPLE 'class-specific_95_percentile' OUTPUT_DIR './output/class-specific_95_percentile'
python train_net.py --resume --num-gpus 4 --config configs/Faster-RCNN/nightowls/faster_rcnn_R_50_FPN_ut2_sup0.08_run0.yaml SOLVER.IMG_PER_BATCH_LABEL 4 SOLVER.IMG_PER_BATCH_UNLABEL 4 MODEL.WEIGHTS /home/hkhachatrian/unbiased_teacher/unbiased-teacher-v2/output/burn_up_250_const_threshold_sup_loss_weight_1/model_0000249.pth EXPERIMENT_NAME 'equal_97_percentile' SEMISUPNET.PSEUDO_BBOX_SAMPLE 'equal_97_percentile' OUTPUT_DIR './output/equal_97_percentile'
python train_net.py --resume --num-gpus 4 --config configs/Faster-RCNN/nightowls/faster_rcnn_R_50_FPN_ut2_sup0.08_run0.yaml SOLVER.IMG_PER_BATCH_LABEL 4 SOLVER.IMG_PER_BATCH_UNLABEL 4 MODEL.WEIGHTS /home/hkhachatrian/unbiased_teacher/unbiased-teacher-v2/output/burn_up_250_const_threshold_sup_loss_weight_1/model_0000249.pth EXPERIMENT_NAME 'class-specific_97_percentile' SEMISUPNET.PSEUDO_BBOX_SAMPLE 'class-specific_97_percentile' OUTPUT_DIR './output/class-specific_97_percentile'
python train_net.py --resume --num-gpus 4 --config configs/Faster-RCNN/nightowls/faster_rcnn_R_50_FPN_ut2_sup0.08_run0.yaml SOLVER.IMG_PER_BATCH_LABEL 4 SOLVER.IMG_PER_BATCH_UNLABEL 4 MODEL.WEIGHTS /home/hkhachatrian/unbiased_teacher/unbiased-teacher-v2/output/burn_up_250_const_threshold_sup_loss_weight_1/model_0000249.pth EXPERIMENT_NAME 'equal_99_percentile' SEMISUPNET.PSEUDO_BBOX_SAMPLE 'equal_99_percentile' OUTPUT_DIR './output/equal_99_percentile'
python train_net.py --resume --num-gpus 4 --config configs/Faster-RCNN/nightowls/faster_rcnn_R_50_FPN_ut2_sup0.08_run0.yaml SOLVER.IMG_PER_BATCH_LABEL 4 SOLVER.IMG_PER_BATCH_UNLABEL 4 MODEL.WEIGHTS /home/hkhachatrian/unbiased_teacher/unbiased-teacher-v2/output/burn_up_250_const_threshold_sup_loss_weight_1/model_0000249.pth EXPERIMENT_NAME 'class-specific_99_percentile' SEMISUPNET.PSEUDO_BBOX_SAMPLE 'class-specific_99_percentile' OUTPUT_DIR './output/class-specific_99_percentile'
python train_net.py --resume --num-gpus 4 --config configs/Faster-RCNN/nightowls/faster_rcnn_R_50_FPN_ut2_sup0.08_run0.yaml SOLVER.IMG_PER_BATCH_LABEL 4 SOLVER.IMG_PER_BATCH_UNLABEL 4 MODEL.WEIGHTS /home/hkhachatrian/unbiased_teacher/unbiased-teacher-v2/output/burn_up_250_const_threshold_sup_loss_weight_1/model_0000249.pth EXPERIMENT_NAME 'equal_99.9_percentile' SEMISUPNET.PSEUDO_BBOX_SAMPLE 'equal_99.9_percentile' OUTPUT_DIR './output/equal_99.9_percentile'
python train_net.py --resume --num-gpus 4 --config configs/Faster-RCNN/nightowls/faster_rcnn_R_50_FPN_ut2_sup0.08_run0.yaml SOLVER.IMG_PER_BATCH_LABEL 4 SOLVER.IMG_PER_BATCH_UNLABEL 4 MODEL.WEIGHTS /home/hkhachatrian/unbiased_teacher/unbiased-teacher-v2/output/burn_up_250_const_threshold_sup_loss_weight_1/model_0000249.pth EXPERIMENT_NAME 'class-specific_99.9_percentile' SEMISUPNET.PSEUDO_BBOX_SAMPLE 'class-specific_99.9_percentile' OUTPUT_DIR './output/class-specific_99.9_percentile'






